apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: pod-preset-example
spec:
  selector:
    matchLabels:
      app: command-demo-loop
  env:
    - name: DB_PORT
      value: "6379"

