apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: pod-preset-example
spec:
  selector:
    matchLabels:
      app: command-demo-loop
  env:
    - name: DB_PORT
      value: "6379"
  lifecycle:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "export hostname=`hostname` && curl -X POST -H 'Authorization: Bearer token' -H 'Content-type: application/json' --data '{\"channel\":\"general\",\"text\":\"'\"The pod has started: $hostname\"'\"}' https://slack.com/api/chat.postMessage"]

